    ignore:
      - "**/BR.*"
      - "**/R.class"
      - "**/R$*.class"
      - "**/BuildConfig.*"
      - "**/Manifest*.*"
      - "**/*Test*.*"
      - "**/*Mock*.*"
      - "**/*Application*.*"
      - "**/*BpCreate*.*",
      - "**/*BpKey*.*",
      - "**/*BpKeyCreate*.*",
      - "**/*BpKeyShow*.*",
      - "**/*BpShow*.*",
      - "**/*BpStatus*.*",
      - "**/*BpUtil*.*",
      - "**/*RegistrationAlreadyExists*.*"
      - "**/*$ViewInjector*.*"
      - "**/*$ViewBinder*.*"
      - "**/*_MembersInjector.class"
      - "**/Dagger*Component.class"
      - "**/Dagger*Component$Builder.class"
      - "**/*Module_*Factory.class"
      - "**/di/module/*"
      - "**/*Module*.*"
      - "**/*Dagger*.*"
      - "**/*Hilt*.*"
      - "**/*MapperImpl*.*"
      - "**/*$ViewInjector*.*"
      - "**/*$ViewBinder*.*"
      - "**/BuildConfig.*"
      - "**/*Component*.*"
      - "**/*BR*.*"
      - "**/Manifest*.*"
      - "**/*$Lambda$*.*"
      - "**/*Companion*.*"
      - "**/*Module*.*"
      - "**/*Dagger*.*"
      - "**/*Hilt*.*"
      - "**/*$Builder*"
      - "**/*$Parcelable*.*"
      - "**/*MembersInjector*.*"
      - "**/*_MembersInjector.class"
      - "**/*_Factory*.*"
      - "**/*_Provide*Factory*.*"
      - "**/*Extensions*.*"
      - "**/*$Result.*"
      - "**/*$Result$*.*"
      - "**/me/**/*.*"
      - "**/api"
      - "**/org/**/*.*"
